chrisrhymes/bulma-clean-theme

_includes/head.html

This fixes the url by respecting Jekylls `site.baseurl` and uses png icons which seem to be better supported than ico icons.

Explicitely reference shortcut icon

---

_layouts/default.html

The current implementation allows setting `page.hero_height`, which can be one of `is-small`, `is-medium`, `is-large`. There is no user option to disable hero completely. This patch adds `page.no_hero`, which when set, completely disables the hero section.
I like the style, but hero takes too much of the vertical space (even when `is-small`), plus I prefer to render the page title using Markdown, so it shows as a page title also when rendered directly by GitHub or VS Code markdown preview.
On the other hand, I guess I can just copy `default.html` to my site's `_layouts`, remove the hero include, call it `no_hero.html` and use this as a default layout. And since I am also no web dev, with no experience with Jekyll, I could be totally off. So I am leaving this PR here more as question, if …

Added `page.no_hero` to allow skipping hero section.

---

_includes/callouts.html

Remove hardcoded callout size of `is-medium` and instead, let it be set by style attribute in callouts yaml.
For example `home_callouts.yaml`
```
style: is-light is-small
```

Remove hardcoded size

---

_includes/pagination.html

Thanks so much for this theme, I really like the way it looks, and I appreciate all the extra features.
I found that the pagination controls link the number 1 to the previous page instead of the first page, perhaps because you can't just link to `/blog/page1`. I've implemented the correct link by splitting on `/`, popping the `page:num` or whatever pattern is configured, and then rejoining on `/`. I think this is general enough to cover any configuration that the pagination module will support.

Fix pagination link to first page

---

_includes/callouts.html
_includes/footer.html
_includes/head.html
_includes/header.html
_includes/hero.html
_includes/menubar.html
_includes/showcase.html
_includes/tabs.html
_layouts/product-category.html

This theme is working well on my GitHub pages, but I ran into a small problem. I can't use an external URL in the navigation links. For example, I tried adding this to the end of `navigation.yml`:
```
- name: GitHub
link: https://github.com/chrisrhymes/bulma-clean-theme
```
Instead of using that link, though, it used this one: `http://localhost:4000/bulma-clean-themehttps://github.com/chrisrhymes/bulma-clean-theme`. Obviously, it's prepending the site's base URL to what's already an absolute URL. Luckily, Jekyll has a filter that does just what we need: [`absolute_url`]. It detects when its parameter is already absolute, and leaves it unchanged.
This PR replaces `prepend: site.baseurl` with `absolute_url` wherever I thought it made sense.
[`absolute_url`]: …

Replace prepend filter with absolute_url to support external links.

---

_includes/callouts.html
_includes/footer.html
_includes/head.html
_includes/header.html
_includes/hero.html
_includes/menubar.html
_includes/showcase.html
_includes/tabs.html
_layouts/product-category.html

Avoids problems with switching from https to http.
I misunderstood the `absolute_url` and `relative_url` filters in [Jekyll]. `absolute_url` includes the protocol, host, and path, but that unfortunately means that it forces the protocol to http. Modern versions of Chrome, at least, warn users that http is not secure, so it's not nice to force browsers to http when the current page is being viewed through https.
Luckily, `relative_url` does what we need. I didn't use it originally, because I confused "relative path" with "relative URL". `relative_url` creates a relative URL with an absolute path. See the examples in the [Jekyll] docs for details.
All that saiid, this PR just switches all the places that I originally used `absolute_url` to now use `relative_url`.
[Jekyll]: …

Correction to #49, switch from absolute_url to relative_url.

---

README.md
_config.yml
_includes/head.html

Resolves issue #71 
The default is set to '#ffffff' and can be overridden in the site's `_config.yml` file if needed.

Added theme color meta tag

---

README.md
_layouts/default.html
bulma-clean-theme.gemspec
page-with-contents.md

This is inspired by #57 by @kazkansouh but is a simplified implementation. 
This allows the contents to be where the menubar is normally by setting `menubar_toc: true` in the page's front matter instead of `toc: true`.

Allow contents in menubar location

---

_layouts/default.html

While `menubar_toc` is active, the content width is still set as `is-12`. This should fix the issue.

Fix content width when menubar_toc is enabled

---

_includes/head.html

`jekyll-seo-tag` already outputs a (more customizable) `<title>` tag

Remove <title> from head.html

---

_config.yml
_layouts/default.html

A `lang` attribute is [considered essential](https://www.w3schools.com/tags/ref_language_codes.asp)

support HTML lang tag

---

README.md

For height properties, is-fullheight should be used instead of is-fullwidth.

Doc: Fix hero_height example

---

_includes/header.html

Highlight first level navigation items also when a child page is active. This provides more usability in many simple cases where the menu items are links to pages in a nested structure...

Highlight section when subpage is active

---

README.md
bulma-clean-theme.gemspec

This PR updates the dependency range for Jekyll such that the theme can be used with both the latest version of Jekyll (4.2), as well as the version compatible with the GitHub Pages gem (3.9).
The reason I am suggesting this change is that I want to use this theme for a new Jekyll site that I am **not** deploying using the GitHub Pages gem, and I would like to have that site start on a newer version of Jekyll since the sass dependency in Jekyll v3.9 is end of life, and in general I would much prefer starting a new project with latest versions for maintainability and access to new features, etc. Also, see the comment I left in issue [#26](https://github.com/chrisrhymes/bulma-clean-theme/issues/26#issuecomment-1032135272).
Testing:
- To test that this theme works with Jekyll v4, I installed …

Allow Jekyll v4 while keeping the theme compatible with the GitHub Pages gem

---

_includes/head.html

Includes the meta tag for the jekyll-feed plugin, if its config is present.

Added jekyll-feed meta to page head include

---

_includes/image-modal.html
_sass/_layout.scss
docs/page-components/image-modal.md

- Replace the alpine js shorthand `@click` with `x-on:click` and `:class` with `x-bind:class`
- Add x-cloak to hide the modal on initial render
- Add example to the image modal docs page

Fix image modal by replacing alpine.js shorthand syntax

---

_config.yml
_data/docs_menu.yml
_includes/cookie-banner.html
_includes/google-analytics.html
_layouts/default.html
cookie-policy.md
docs/page-components/cookie-banner.md

Add a cookie banner to the theme and update Google Analytics to v4 using [Google consent mode](https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced).

Add cookie banner

---

README.md
_posts/2019-02-09-getting-started-with-bulma-clean-theme.markdown
_posts/2020-05-08-creating-a-docs-site-with-bulma-clean-theme.markdown
docs/getting-started/installation.md
docs/getting-started/upgrading-to-v1.md
index.md

Resolves #154 
Update references for remote_theme to use `@` as per the remote_theme gem documentation.

Fix remote_theme docs

---

_includes/cookie-banner.html
_includes/google-analytics.html
_includes/head.html
bulma-clean-theme.gemspec
changelog.txt

Update Google Analytics script to set default consent as granted if cookies are already accepted.

Set default consent as granted if cookies accepted

---

_includes/cookie-banner.html
_layouts/product-category.html
docs/products/category-page.md
docs/products/product-pages.md

- Allow using a custom collection name for products, but defaults to 'products'.
- Update the cookie expiry time to 365 days to prevent return visitors having to keep accepting/rejecting cookies.
- Update the docs for the product pages

Allow custom collection name for products
